#!/bin/bash
# <%= @puppet_header %>
# <%=  __FILE__.gsub(/.*?puppet\//,@fqdn + ':') %>
export HOME=~<%= @user %>
export PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin
cd $HOME
if [ "z" == "z$1" ] ; then
   echo "usage $0 script_name"
   exit 1
fi
script="<%= @steam_script_dir %>/$1.steam"
if [ -r $script ] ; then
    ./steamcmd.sh +runscript $script
else
    echo "File $script not found!"
fi
